In [1]:
import pdfplumber
import pandas as pd

In [2]:
file_path = 'MT.pdf'

word_dict = []

with pdfplumber.open(file_path) as pdf:
    all_tables = []

    page_num = 0

    for page in pdf.pages:

        tables = page.extract_tables()

        for table in tables:
            df = pd.DataFrame(table)
            all_tables.append(df)

        words = page.extract_words()

        for word in words:
            word_dict.append({'Word': word['text'],
                             'x': word['x0'],
                             'Page': page_num})
        page_num += 1

In [7]:
all_tables[0]

,0,1,2,3
0,Preferred Agents,Non-Preferred,Non-Preferred Cont.,Limitations
1,Butrans Patch #,Belbuca #\nbuprenorphine (Butrans) #\nConzip E...,morphine ER (Avinza) #\nmorphine sulfate ER ca...,No more than one long
2,morphine sulfate SR tab #,None,None,acting opioid allowed.
3,,None,None,
4,,None,None,# Quantity limits apply
5,,None,None,
6,,None,None,% Clinical criteria applies
7,,None,None,
8,,None,None,MME restriction applies to
9,,None,None,None
10,None,None,None,this class
11,,None,None,None
12,None,None,None,
13,,None,None,None

In [3]:
np_correct_x_cord = 217.44
np_incorrect_x_cord = 221.04


word_df = pd.DataFrame(word_dict)

In [4]:
word_df

                       Word           x  Page
0                   Montana  152.160000     0
1                Healthcare  202.675920     0
2                  Programs  264.477192     0
3                 Preferred  321.347616     0
4                      Drug  375.581328     0
...                     ...         ...   ...
9659  294-1350/406-513-1928  361.183920    32
9660                   Page  513.590160    32
9661                     33  535.788600    32
9662                     of  548.387280    32
9663                     33  558.590040    32

[9664 rows x 3 columns]

In [5]:
word_df[word_df['x'] > 217][word_df['x'] < 218]

C:\Users\hgarrison\AppData\Local\Temp\ipykernel_15772\4066922755.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  word_df[word_df['x'] > 217][word_df['x'] < 218]

                      Word        x  Page
85           Non-Preferred  217.440     0
92                 Belbuca  217.440     0
108          buprenorphine  217.440     0
118                 Conzip  217.449     0
124              Duragesic  217.449     0
...                    ...      ...   ...
9478                Clodan  217.440    31
9615         Non-Preferred  217.440    32
9620  etonogestrel/ethinyl  217.440    32
9636      dichlorphenamide  217.440    32
9638             miglustat  217.440    32

[881 rows x 3 columns]

In [ ]:
table_nums = []
p_agents = []
np_agents = []
np_agents2 = []

table_num = 0

for table in all_tables:
    for index, row in table.iterrows():
        table_nums.append(table_num)
        p_agents.append(table[0][index])
        np_agents.append(table[1][index])
        np_agents2.append(table[2][index])


    table_num += 1


df = pd.DataFrame([table_nums, p_agents, np_agents, np_agents2]).transpose()
df.columns = ['table_num', 'Preferred Agents', 'Non-Preferred', 'Non-Preferred Cont.']
df = df[df['Preferred Agents'] != 'Preferred Agents']

df = df.melt(id_vars='table_num', value_name='Products', var_name='Status')
df[df['Status'] == 'Non-Preferred Cont.']['Products'][1480].split('\n')

['morphine ER (Avinza) #',
 'morphine sulfate ER cap',
 '(Kadian) #',
 'MS Contin * #',
 'oxycodone ER #',
 'OxyContin #',
 'oxymorphone ER #',
 'tramadol ER % #',
 'Zohydro ER %']

In [75]:
df

,0,1,2,3
0,Preferred Agents,Non-Preferred,Non-Preferred Cont.,Limitations
1,Nuvaring,etonogestrel/ethinyl estradiol\nvaginal ring\n...,N/A,Use of generic will require
2,,None,None,prior authorization and
3,,None,None,clinical rationale
4,Keveyis,None,None,
5,,None,None,None
6,Zavesca,None,None,None
7,,None,None,None